import { writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { CORE_BLOCKS } from '@stepkids/blocks';
import { checkLevel } from '@stepkids/engine';
import { CHARACTERS, SEED_WORLDS, TIERS_META, costumesOf } from '../src';

/**
 * Generates supabase/seed.sql from the typed content: tiers, characters, the block catalog
 * and the seed worlds with their levels (version 1, published, with the pass-check result).
 */
const lit = (value: string | null | undefined): string =>
  value === null || value === undefined ? 'null' : `'${value.replace(/'/g, "''")}'`;
const json = (value: unknown): string => `${lit(JSON.stringify(value))}::jsonb`;
const textArray = (values: string[]): string => `array[${values.map(lit).join(', ')}]::text[]`;

const lines: string[] = [
  '-- Generated by packages/content/scripts/build-sql-seed.ts — do not edit by hand.',
  '-- Regenerate with: pnpm --filter @stepkids/content build:sql-seed',
  '',
  'begin;',
  '',
];

for (const tier of TIERS_META) {
  lines.push(
    `insert into public.tiers (id, "order", title, scene_mode, editor_mode, unlock_share) values (${tier.id}, ${tier.id}, ${lit(tier.title)}, '${tier.sceneMode}', '${tier.editorMode}', ${tier.unlockShare}) on conflict (id) do update set title = excluded.title, scene_mode = excluded.scene_mode, editor_mode = excluded.editor_mode, unlock_share = excluded.unlock_share;`,
  );
}
lines.push('');

for (const character of CHARACTERS) {
  lines.push(
    `insert into public.characters (id, name, role, costumes, voice_profile, unlock_rule) values (${lit(character.id)}, ${lit(character.name)}, ${lit(character.role)}, ${json(character.costumes)}, ${json(character.voice)}, ${json(character.unlockedBy ? { world: character.unlockedBy } : {})}) on conflict (id) do update set name = excluded.name, costumes = excluded.costumes, voice_profile = excluded.voice_profile, unlock_rule = excluded.unlock_rule;`,
  );
}
lines.push('');

CORE_BLOCKS.forEach((block, index) => {
  lines.push(
    `insert into public.block_types (id, category, tier_min, label, icon, voice_text, shape, params_schema, behavior, codegen, enabled, sort) values (${lit(block.type)}, ${lit(block.category)}, ${block.tier}, ${lit(block.label)}, ${lit(block.icon)}, ${lit(block.voice)}, ${lit(block.shape)}, ${json(block.params)}, ${json(block.behavior)}, ${json({ ...block.codegen, voiceTemplate: block.voiceTemplate ?? null, stacks: block.stacks ?? [] })}, true, ${index}) on conflict (id) do update set label = excluded.label, icon = excluded.icon, voice_text = excluded.voice_text, params_schema = excluded.params_schema, behavior = excluded.behavior, codegen = excluded.codegen, sort = excluded.sort;`,
  );
});
lines.push('');

for (const world of SEED_WORLDS) {
  lines.push(
    `insert into public.worlds (id, tier_id, "order", title, voice_text, island, unlock_rule, reward, status) values (${lit(world.id)}, ${world.tier}, ${world.order}, ${lit(world.title)}, ${lit(world.voice)}, ${lit(world.island)}, ${json(world.unlock)}, ${json(world.reward ?? {})}, 'published') on conflict (id) do nothing;`,
  );
  world.levels.forEach(({ id, content }, index) => {
    const check = checkLevel(content, { costumes: costumesOf });
    if (!check.ok) throw new Error(`Level ${id} does not pass: ${check.problems.join('; ')}`);
    const checkResult = {
      ok: true,
      blocks: check.result?.blocks,
      steps: check.result?.steps,
      stars: check.result?.stars,
      problems: [],
    };
    lines.push(
      `insert into public.levels (id, world_id, "order", status) values (${lit(id)}, ${lit(world.id)}, ${index + 1}, 'draft') on conflict (id) do nothing;`,
      `insert into public.level_versions (level_id, version, kind, task_text, scene, allowed_blocks, block_limit, starter_program, goals, stars_rule, hints, reference_solution, check_result) values (${lit(id)}, 1, ${lit(content.kind)}, ${lit(content.taskText)}, ${json(content.scene)}, ${textArray(content.allowedBlocks)}, ${content.blockLimit ?? 'null'}, ${content.starterProgram ? json(content.starterProgram) : 'null'}, ${json(content.goals)}, ${json(content.stars)}, ${json(content.hints)}, ${content.reference ? json(content.reference) : 'null'}, ${json(checkResult)}) on conflict do nothing;`,
      `update public.levels set current_version = 1, status = 'published' where id = ${lit(id)} and current_version is null;`,
    );
  });
  lines.push('');
}

lines.push('commit;', '');
const target = fileURLToPath(new URL('../../../db/seed.sql', import.meta.url));
writeFileSync(target, lines.join('\n'));
console.warn(`wrote ${target}`);
