import type { BlockCategory, BlockDef, BlockShape, ChoiceOption, ParamDef } from './types';
import type { Tier } from '../level';

/**
 * Blocks of tiers 3–4 (free scene, puzzle editor). Value and condition slots accept either a
 * literal typed into the puzzle or another block plugged in.
 */

const num = (name: string, voice: string, value: number): ParamDef => ({
  name,
  kind: 'slot',
  voice,
  accepts: 'value',
  default: value,
});
const text = (name: string, voice: string, value: string): ParamDef => ({
  name,
  kind: 'slot',
  voice,
  accepts: 'value',
  default: value,
});
const cond = (name = 'cond'): ParamDef => ({
  name,
  kind: 'slot',
  voice: 'условие',
  accepts: 'condition',
});

export const KEYS: ChoiceOption[] = [
  { value: 'space', label: 'пробел', icon: 'keyboard', voice: 'пробел' },
  { value: 'left', label: 'влево', icon: 'arrow-left', voice: 'стрелка влево' },
  { value: 'right', label: 'вправо', icon: 'arrow-right', voice: 'стрелка вправо' },
  { value: 'up', label: 'вверх', icon: 'arrow-up', voice: 'стрелка вверх' },
  { value: 'down', label: 'вниз', icon: 'arrow-down', voice: 'стрелка вниз' },
  { value: 'any', label: 'любая', icon: 'keyboard', voice: 'любая клавиша' },
];

const COMPARISONS: Array<{
  type: string;
  label: string;
  op: string;
  js: string;
  py: string;
  voice: string;
}> = [
  { type: 'op_lt', label: '<', op: 'lt', js: '<', py: '<', voice: 'меньше' },
  { type: 'op_eq', label: '=', op: 'eq', js: '===', py: '==', voice: 'равно' },
  { type: 'op_gt', label: '>', op: 'gt', js: '>', py: '>', voice: 'больше' },
];

const ARITHMETIC: Array<{
  type: string;
  label: string;
  op: string;
  js: string;
  voice: string;
  icon: string;
}> = [
  { type: 'op_add', label: '+', op: 'add', js: '+', voice: 'плюс', icon: 'plus' },
  { type: 'op_sub', label: '−', op: 'sub', js: '-', voice: 'минус', icon: 'minus' },
  { type: 'op_mul', label: '×', op: 'mul', js: '*', voice: 'умножить', icon: 'x' },
  { type: 'op_div', label: '÷', op: 'div', js: '/', voice: 'разделить', icon: 'divide' },
];

function def(
  type: string,
  category: BlockCategory,
  tier: Tier,
  shape: BlockShape,
  icon: string,
  label: string,
  voice: string,
  params: ParamDef[],
  primitive: string,
  codegen: { js: string; py: string },
  extra: Partial<BlockDef> = {},
): BlockDef {
  return {
    type,
    category,
    tier,
    shape,
    icon,
    label,
    voice,
    params,
    behavior: { primitive },
    codegen,
    ...extra,
  };
}

export const ADVANCED_BLOCKS: BlockDef[] = [
  // Events
  def(
    'event_key',
    'events',
    3,
    'hat',
    'keyboard',
    'Клавиша',
    'когда нажата клавиша',
    [{ name: 'key', kind: 'choice', voice: 'какая клавиша', options: KEYS, default: 'space' }],
    'event.key',
    {
      js: 'onKey({key}, () => {\n{STACK}\n});',
      py: '@on_key({key})\ndef on_key():\n{STACK}',
    },
    { text: 'когда нажата {key}' },
  ),
  def(
    'event_message',
    'events',
    3,
    'hat',
    'mail-open',
    'Получено',
    'когда получено сообщение',
    [
      {
        name: 'message',
        kind: 'dynamic',
        voice: 'какое сообщение',
        source: 'messages',
        default: 'сигнал',
      },
    ],
    'event.message',
    {
      js: 'onMessage({message}, () => {\n{STACK}\n});',
      py: '@on_message({message})\ndef on_message():\n{STACK}',
    },
    { text: 'когда получено {message}' },
  ),
  def(
    'event_broadcast',
    'events',
    3,
    'command',
    'send',
    'Отправить',
    'отправить сообщение',
    [
      {
        name: 'message',
        kind: 'dynamic',
        voice: 'какое сообщение',
        source: 'messages',
        default: 'сигнал',
      },
    ],
    'events.broadcast',
    {
      js: 'broadcast({message});',
      py: 'broadcast({message})',
    },
    { text: 'отправить {message}' },
  ),

  // Motion (free scene)
  def(
    'motion_move',
    'motion',
    3,
    'command',
    'footprints',
    'Иди',
    'иди вперёд',
    [num('steps', 'сколько шагов', 10)],
    'free.move',
    { js: 'move({steps});', py: 'move({steps})' },
    { text: 'иди {steps} шагов' },
  ),
  def(
    'motion_turn_cw',
    'motion',
    3,
    'command',
    'rotate-cw',
    'Поворот ↻',
    'повернись по часовой стрелке',
    [num('degrees', 'на сколько градусов', 15)],
    'free.turn',
    { js: 'turnRight({degrees});', py: 'turn_right({degrees})' },
    {
      text: 'повернись ↻ на {degrees} градусов',
      behavior: { primitive: 'free.turn', with: { sign: 1 } },
    },
  ),
  def(
    'motion_turn_ccw',
    'motion',
    3,
    'command',
    'rotate-ccw',
    'Поворот ↺',
    'повернись против часовой стрелки',
    [num('degrees', 'на сколько градусов', 15)],
    'free.turn',
    { js: 'turnLeft({degrees});', py: 'turn_left({degrees})' },
    {
      text: 'повернись ↺ на {degrees} градусов',
      behavior: { primitive: 'free.turn', with: { sign: -1 } },
    },
  ),
  def(
    'motion_point',
    'motion',
    3,
    'command',
    'compass',
    'Смотри',
    'повернись в направлении',
    [num('direction', 'направление', 90)],
    'free.point',
    { js: 'pointInDirection({direction});', py: 'point_in_direction({direction})' },
    { text: 'смотри в направлении {direction}' },
  ),
  def(
    'motion_goto',
    'motion',
    3,
    'command',
    'locate',
    'Иди в x y',
    'иди в точку',
    [num('x', 'икс', 0), num('y', 'игрек', 0)],
    'free.goto',
    { js: 'goTo({x}, {y});', py: 'go_to({x}, {y})' },
    { text: 'иди в x {x} y {y}' },
  ),
  def(
    'motion_glide',
    'motion',
    3,
    'command',
    'wind',
    'Плыви к',
    'плыви к точке',
    [num('seconds', 'сколько секунд', 1), num('x', 'икс', 0), num('y', 'игрек', 0)],
    'free.glide',
    { js: 'await glide({seconds}, {x}, {y});', py: 'glide({seconds}, {x}, {y})' },
    { text: 'плыви {seconds} сек к x {x} y {y}' },
  ),
  def(
    'motion_change_x',
    'motion',
    3,
    'command',
    'move-horizontal',
    'Сдвинь x',
    'сдвинь по иксу',
    [num('dx', 'на сколько', 10)],
    'free.changeX',
    { js: 'changeX({dx});', py: 'change_x({dx})' },
    { text: 'сдвинь x на {dx}' },
  ),
  def(
    'motion_change_y',
    'motion',
    3,
    'command',
    'move-vertical',
    'Сдвинь y',
    'сдвинь по игреку',
    [num('dy', 'на сколько', 10)],
    'free.changeY',
    { js: 'changeY({dy});', py: 'change_y({dy})' },
    { text: 'сдвинь y на {dy}' },
  ),
  def(
    'motion_bounce',
    'motion',
    3,
    'command',
    'undo-2',
    'От края',
    'если край, оттолкнись',
    [],
    'free.bounce',
    { js: 'bounceOnEdge();', py: 'bounce_on_edge()' },
    { text: 'если край, оттолкнись' },
  ),
  def('motion_x', 'motion', 3, 'value', 'move-horizontal', 'x', 'икс', [], 'free.x', {
    js: 'x',
    py: 'x',
  }),
  def('motion_y', 'motion', 3, 'value', 'move-vertical', 'y', 'игрек', [], 'free.y', {
    js: 'y',
    py: 'y',
  }),
  def(
    'motion_direction',
    'motion',
    3,
    'value',
    'compass',
    'Направление',
    'направление',
    [],
    'free.direction',
    { js: 'direction', py: 'direction' },
    { text: 'направление' },
  ),

  // Looks
  def(
    'looks_say_for',
    'looks',
    3,
    'command',
    'message-square',
    'Скажи на',
    'скажи и подожди',
    [text('text', 'что сказать', 'Привет!'), num('seconds', 'сколько секунд', 2)],
    'looks.sayFor',
    { js: 'await say({text}, {seconds});', py: 'say({text}, {seconds})' },
    { text: 'скажи {text} {seconds} сек' },
  ),
  def(
    'looks_size',
    'looks',
    3,
    'command',
    'scaling',
    'Размер',
    'задай размер',
    [num('size', 'какой размер', 100)],
    'free.size',
    { js: 'setSize({size});', py: 'set_size({size})' },
    { text: 'размер {size} %' },
  ),
  def(
    'looks_size_change',
    'looks',
    3,
    'command',
    'zoom-in',
    'Больше на',
    'стань больше',
    [num('by', 'на сколько', 10)],
    'free.sizeChange',
    { js: 'changeSize({by});', py: 'change_size({by})' },
    { text: 'стань больше на {by}' },
  ),
  def(
    'looks_front',
    'looks',
    3,
    'command',
    'layers',
    'Вперёд',
    'выйди на передний план',
    [],
    'free.front',
    { js: 'goToFront();', py: 'go_to_front()' },
    { text: 'выйди вперёд' },
  ),

  // Control
  def(
    'control_if',
    'control',
    3,
    'wrapper',
    'split',
    'Если',
    'если',
    [cond()],
    'control.if',
    { js: 'if ({cond}) {\n{THEN}\n}', py: 'if {cond}:\n{THEN}' },
    { stacks: ['THEN'], text: 'если {cond} то' },
  ),
  def(
    'control_if_else',
    'control',
    3,
    'wrapper',
    'git-fork',
    'Если-иначе',
    'если, иначе',
    [cond()],
    'control.ifElse',
    { js: 'if ({cond}) {\n{THEN}\n} else {\n{ELSE}\n}', py: 'if {cond}:\n{THEN}\nelse:\n{ELSE}' },
    { stacks: ['THEN', 'ELSE'], text: 'если {cond} то' },
  ),
  def(
    'control_while',
    'control',
    3,
    'wrapper',
    'refresh-cw',
    'Пока',
    'повторяй, пока',
    [cond()],
    'control.while',
    { js: 'while ({cond}) {\n{DO}\n}', py: 'while {cond}:\n{DO}' },
    { stacks: ['DO'], text: 'пока {cond}' },
  ),
  def(
    'control_stop',
    'control',
    3,
    'cap',
    'octagon',
    'Стоп',
    'стоп',
    [
      {
        name: 'what',
        kind: 'choice',
        voice: 'что остановить',
        default: 'all',
        options: [
          { value: 'all', label: 'всё', icon: 'octagon', voice: 'всё' },
          { value: 'this', label: 'эту программу', icon: 'octagon', voice: 'эту программу' },
        ],
      },
    ],
    'control.stop',
    { js: 'stop({what});', py: 'stop({what})' },
    { text: 'стоп {what}' },
  ),

  // Sensing
  def(
    'sensing_touching',
    'sensing',
    3,
    'condition',
    'hand',
    'Касается?',
    'касается',
    [{ name: 'target', kind: 'dynamic', voice: 'чего', source: 'actors', default: 'edge' }],
    'sensing.touching',
    { js: 'touching({target})', py: 'touching({target})' },
    { text: 'касается {target}?' },
  ),
  def(
    'sensing_distance',
    'sensing',
    3,
    'value',
    'ruler',
    'Расстояние',
    'расстояние до',
    [{ name: 'target', kind: 'dynamic', voice: 'до кого', source: 'actors', default: '' }],
    'sensing.distance',
    { js: 'distanceTo({target})', py: 'distance_to({target})' },
    { text: 'расстояние до {target}' },
  ),
  def(
    'sensing_ask',
    'sensing',
    3,
    'command',
    'circle-help',
    'Спроси',
    'спроси и жди ответа',
    [text('question', 'какой вопрос', 'Как тебя зовут?')],
    'sensing.ask',
    { js: 'answer = await ask({question});', py: 'answer = ask({question})' },
    { text: 'спроси {question} и жди' },
  ),
  def(
    'sensing_answer',
    'sensing',
    3,
    'value',
    'message-circle-reply',
    'Ответ',
    'ответ',
    [],
    'sensing.answer',
    { js: 'answer', py: 'answer' },
    { text: 'ответ' },
  ),
  def(
    'sensing_timer',
    'sensing',
    3,
    'value',
    'timer',
    'Таймер',
    'таймер',
    [],
    'sensing.timer',
    { js: 'timer()', py: 'timer()' },
    { text: 'таймер' },
  ),
  def(
    'sensing_reset_timer',
    'sensing',
    3,
    'command',
    'timer-reset',
    'Таймер 0',
    'сбросить таймер',
    [],
    'sensing.resetTimer',
    { js: 'resetTimer();', py: 'reset_timer()' },
    { text: 'сбросить таймер' },
  ),

  // Operators
  ...ARITHMETIC.map((op) =>
    def(
      op.type,
      'operators',
      3,
      'value',
      op.icon,
      op.label,
      op.voice,
      [num('a', 'первое', 0), num('b', 'второе', 0)],
      'op.arith',
      { js: `({a} ${op.js} {b})`, py: `({a} ${op.js === '/' ? '/' : op.js} {b})` },
      {
        text: `{a} ${op.label} {b}`,
        behavior: { primitive: 'op.arith', with: { op: op.op } },
      },
    ),
  ),
  def(
    'op_random',
    'operators',
    3,
    'value',
    'dice-5',
    'Случайное',
    'случайное число',
    [num('from', 'от', 1), num('to', 'до', 10)],
    'op.random',
    { js: 'random({from}, {to})', py: 'random.randint({from}, {to})' },
    { text: 'случайное от {from} до {to}' },
  ),
  ...COMPARISONS.map((op) =>
    def(
      op.type,
      'operators',
      3,
      'condition',
      'equal',
      op.label,
      op.voice,
      [num('a', 'первое', 0), num('b', 'второе', 50)],
      'op.compare',
      { js: `({a} ${op.js} {b})`, py: `({a} ${op.py} {b})` },
      {
        text: `{a} ${op.label} {b}`,
        behavior: { primitive: 'op.compare', with: { op: op.op } },
      },
    ),
  ),
  def(
    'op_and',
    'operators',
    3,
    'condition',
    'ampersand',
    'и',
    'и',
    [cond('a'), cond('b')],
    'op.logic',
    { js: '({a} && {b})', py: '({a} and {b})' },
    { text: '{a} и {b}', behavior: { primitive: 'op.logic', with: { op: 'and' } } },
  ),
  def(
    'op_or',
    'operators',
    3,
    'condition',
    'git-merge',
    'или',
    'или',
    [cond('a'), cond('b')],
    'op.logic',
    { js: '({a} || {b})', py: '({a} or {b})' },
    { text: '{a} или {b}', behavior: { primitive: 'op.logic', with: { op: 'or' } } },
  ),
  def(
    'op_not',
    'operators',
    3,
    'condition',
    'circle-slash',
    'не',
    'не',
    [cond('a')],
    'op.not',
    { js: '!{a}', py: 'not {a}' },
    { text: 'не {a}' },
  ),
  def(
    'op_join',
    'operators',
    3,
    'value',
    'link',
    'Соедини',
    'соедини',
    [text('a', 'первое', 'Привет, '), text('b', 'второе', 'мир')],
    'op.join',
    { js: '(String({a}) + String({b}))', py: '(str({a}) + str({b}))' },
    { text: 'соедини {a} и {b}' },
  ),

  // Data
  def(
    'data_set',
    'data',
    3,
    'command',
    'box',
    'Задай',
    'задай переменную',
    [
      {
        name: 'var',
        kind: 'dynamic',
        voice: 'какую переменную',
        source: 'variables',
        default: 'счёт',
      },
      num('value', 'значение', 0),
    ],
    'data.set',
    { js: '{var} = {value};', py: '{var} = {value}' },
    { text: 'задай {var} = {value}' },
  ),
  def(
    'data_change',
    'data',
    3,
    'command',
    'plus',
    'Измени на',
    'измени переменную',
    [
      {
        name: 'var',
        kind: 'dynamic',
        voice: 'какую переменную',
        source: 'variables',
        default: 'счёт',
      },
      num('by', 'на сколько', 1),
    ],
    'data.change',
    { js: '{var} += {by};', py: '{var} += {by}' },
    { text: 'измени {var} на {by}' },
  ),
  def(
    'data_var',
    'data',
    3,
    'value',
    'box',
    'Переменная',
    'значение переменной',
    [
      {
        name: 'var',
        kind: 'dynamic',
        voice: 'какая переменная',
        source: 'variables',
        default: 'счёт',
      },
    ],
    'data.get',
    { js: '{var}', py: '{var}' },
    { text: '{var}' },
  ),

  // Tier 4: my blocks
  def(
    'procedures_define',
    'myblocks',
    4,
    'hat',
    'puzzle',
    'Мой блок',
    'определить блок',
    [
      {
        name: 'name',
        kind: 'text',
        voice: 'как назвать',
        maxLength: 30,
        default: 'прыжок',
        presets: [],
      },
      { name: 'params', kind: 'text', voice: 'параметры', maxLength: 60, default: '', presets: [] },
    ],
    'procedures.define',
    { js: 'function {name}({params}) {\n{STACK}\n}', py: 'def {name}({params}):\n{STACK}' },
    { text: 'мой блок {name} {params}' },
  ),
  def(
    'procedures_call',
    'myblocks',
    4,
    'command',
    'puzzle',
    'Вызови',
    'вызвать свой блок',
    [
      {
        name: 'name',
        kind: 'dynamic',
        voice: 'какой блок',
        source: 'procedures',
        default: 'прыжок',
      },
      num('arg0', 'первый параметр', 0),
      num('arg1', 'второй параметр', 0),
    ],
    'procedures.call',
    { js: '{name}({arg0}, {arg1});', py: '{name}({arg0}, {arg1})' },
    { text: '{name} {arg0} {arg1}' },
  ),
  def(
    'procedures_param',
    'myblocks',
    4,
    'value',
    'puzzle',
    'Параметр',
    'параметр',
    [
      {
        name: 'name',
        kind: 'text',
        voice: 'какой параметр',
        maxLength: 30,
        default: 'n',
        presets: [],
      },
    ],
    'procedures.param',
    { js: '{name}', py: '{name}' },
    { text: '{name}' },
  ),

  // Tier 4: lists
  def(
    'list_add',
    'data',
    4,
    'command',
    'list-plus',
    'Добавь в',
    'добавь в список',
    [
      text('item', 'что добавить', 'яблоко'),
      {
        name: 'list',
        kind: 'dynamic',
        voice: 'в какой список',
        source: 'lists',
        default: 'список',
      },
    ],
    'list.add',
    { js: '{list}.push({item});', py: '{list}.append({item})' },
    { text: 'добавь {item} в {list}' },
  ),
  def(
    'list_delete',
    'data',
    4,
    'command',
    'list-minus',
    'Удали из',
    'удали из списка',
    [
      num('index', 'какой по счёту', 1),
      {
        name: 'list',
        kind: 'dynamic',
        voice: 'из какого списка',
        source: 'lists',
        default: 'список',
      },
    ],
    'list.delete',
    { js: '{list}.splice({index} - 1, 1);', py: 'del {list}[{index} - 1]' },
    { text: 'удали {index} из {list}' },
  ),
  def(
    'list_clear',
    'data',
    4,
    'command',
    'list-x',
    'Очисти',
    'очисти список',
    [{ name: 'list', kind: 'dynamic', voice: 'какой список', source: 'lists', default: 'список' }],
    'list.clear',
    { js: '{list}.length = 0;', py: '{list}.clear()' },
    { text: 'очисти {list}' },
  ),
  def(
    'list_item',
    'data',
    4,
    'value',
    'list-ordered',
    'Элемент',
    'элемент списка',
    [
      num('index', 'какой по счёту', 1),
      { name: 'list', kind: 'dynamic', voice: 'какого списка', source: 'lists', default: 'список' },
    ],
    'list.item',
    { js: '{list}[{index} - 1]', py: '{list}[{index} - 1]' },
    { text: 'элемент {index} из {list}' },
  ),
  def(
    'list_length',
    'data',
    4,
    'value',
    'list',
    'Длина',
    'длина списка',
    [{ name: 'list', kind: 'dynamic', voice: 'какого списка', source: 'lists', default: 'список' }],
    'list.length',
    { js: '{list}.length', py: 'len({list})' },
    { text: 'длина {list}' },
  ),
  def(
    'list_contains',
    'data',
    4,
    'condition',
    'list-checks',
    'Есть в?',
    'есть в списке',
    [
      {
        name: 'list',
        kind: 'dynamic',
        voice: 'в каком списке',
        source: 'lists',
        default: 'список',
      },
      text('item', 'что', 'яблоко'),
    ],
    'list.contains',
    { js: '{list}.includes({item})', py: '({item} in {list})' },
    { text: '{list} содержит {item}?' },
  ),

  // Tier 4: clones
  def(
    'control_create_clone',
    'control',
    4,
    'command',
    'copy',
    'Клонируй',
    'клонируй себя',
    [],
    'clone.create',
    { js: 'createClone();', py: 'create_clone()' },
    { text: 'клонируй себя' },
  ),
  def(
    'event_clone_start',
    'control',
    4,
    'hat',
    'copy',
    'Я клон',
    'когда я начинаю как клон',
    [],
    'event.cloneStart',
    { js: 'onCloneStart(() => {\n{STACK}\n});', py: '@on_clone_start\ndef on_clone():\n{STACK}' },
    { text: 'когда я начинаю как клон' },
  ),
  def(
    'control_delete_clone',
    'control',
    4,
    'cap',
    'trash-2',
    'Удали клон',
    'удали этот клон',
    [],
    'clone.delete',
    { js: 'deleteClone();', py: 'delete_clone()' },
    { text: 'удали этот клон' },
  ),
];
