import type { BlockDef, ChoiceOption, IntParam, NounForms } from './types';

const SECONDS: NounForms = { one: 'секунду', few: 'секунды', many: 'секунд' };
const TIMES: NounForms = { one: 'раз', few: 'раза', many: 'раз' };

const stepCount: IntParam = {
  name: 'count',
  kind: 'int',
  voice: 'сколько шагов',
  min: 1,
  max: 9,
  default: 1,
  gender: 'm',
};

export const MELODIES: ChoiceOption[] = [
  { value: 'happy', label: 'Весёлая', icon: 'music', voice: 'весёлая песенка' },
  { value: 'lullaby', label: 'Тихая', icon: 'moon', voice: 'тихая песенка' },
  { value: 'fanfare', label: 'Ура', icon: 'party-popper', voice: 'фанфары' },
  { value: 'bells', label: 'Звоночки', icon: 'bell', voice: 'звоночки' },
  { value: 'drum', label: 'Барабан', icon: 'drum', voice: 'барабан' },
];

export const SAY_PRESETS = [
  'Привет!',
  'Ура!',
  'Я молодец!',
  'Пока!',
  'Спасибо!',
  'Мяу!',
  'Гав!',
  'Ку-ку!',
];

export const TOUCH_TARGETS: ChoiceOption[] = [
  { value: 'actor', label: 'Друга', icon: 'users', voice: 'друга' },
  { value: 'star', label: 'Звезду', icon: 'star', voice: 'звезду' },
  { value: 'flag', label: 'Флажок', icon: 'flag', voice: 'флажок' },
  { value: 'key', label: 'Ключ', icon: 'key-round', voice: 'ключ' },
];

function arrow(
  dir: 'right' | 'left' | 'up' | 'down',
  label: string,
  icon: string,
  js: string,
  py: string,
): BlockDef {
  return {
    type: `motion_${dir}`,
    category: 'motion',
    tier: 1,
    shape: 'command',
    icon,
    label,
    voice: label.toLowerCase(),
    voiceTemplate: `${label.toLowerCase()} {count}`,
    params: [stepCount],
    behavior: { primitive: 'motion.step', with: { dir } },
    codegen: { js: `${js}({count});`, py: `${py}({count})` },
  };
}

/** Blocks of tiers 1–2: the grid scene and the ribbon editor. */
export const CORE_BLOCKS: BlockDef[] = [
  {
    type: 'event_start',
    category: 'events',
    tier: 1,
    shape: 'hat',
    icon: 'flag',
    label: 'Старт',
    voice: 'когда старт',
    params: [],
    behavior: { primitive: 'event.start' },
    codegen: { js: 'onStart(() => {\n{STACK}\n});', py: '@on_start\ndef main():\n{STACK}' },
  },
  arrow('right', 'Вправо', 'arrow-right', 'moveRight', 'move_right'),
  arrow('left', 'Влево', 'arrow-left', 'moveLeft', 'move_left'),
  arrow('up', 'Вверх', 'arrow-up', 'moveUp', 'move_up'),
  arrow('down', 'Вниз', 'arrow-down', 'moveDown', 'move_down'),
  {
    type: 'looks_say',
    category: 'looks',
    tier: 1,
    shape: 'command',
    icon: 'message-circle',
    label: 'Скажи',
    voice: 'скажи',
    voiceTemplate: 'скажи: {text}',
    params: [
      {
        name: 'text',
        kind: 'text',
        voice: 'что сказать',
        maxLength: 40,
        default: 'Привет!',
        presets: SAY_PRESETS,
      },
    ],
    behavior: { primitive: 'looks.say' },
    codegen: { js: 'say({text});', py: 'say({text})' },
  },
  {
    type: 'sound_music',
    category: 'sound',
    tier: 1,
    shape: 'command',
    icon: 'music',
    label: 'Музыка',
    voice: 'музыка',
    voiceTemplate: 'музыка: {melody}',
    params: [
      {
        name: 'melody',
        kind: 'choice',
        voice: 'какая музыка',
        options: MELODIES,
        default: 'happy',
      },
    ],
    behavior: { primitive: 'sound.melody' },
    codegen: { js: 'playMelody({melody});', py: 'play_melody({melody})' },
  },
  {
    type: 'control_wait',
    category: 'control',
    tier: 1,
    shape: 'command',
    icon: 'hourglass',
    label: 'Подожди',
    voice: 'подожди',
    voiceTemplate: 'подожди {seconds}',
    params: [
      {
        name: 'seconds',
        kind: 'int',
        voice: 'сколько секунд',
        min: 1,
        max: 5,
        default: 1,
        gender: 'f',
        unit: SECONDS,
      },
    ],
    behavior: { primitive: 'control.wait' },
    codegen: { js: 'await wait({seconds});', py: 'wait({seconds})' },
  },
  {
    type: 'control_repeat',
    category: 'control',
    tier: 2,
    shape: 'wrapper',
    icon: 'repeat',
    label: 'Повтори',
    voice: 'повтори',
    voiceTemplate: 'повтори {times}',
    params: [
      {
        name: 'times',
        kind: 'int',
        voice: 'сколько раз',
        min: 2,
        max: 10,
        default: 2,
        gender: 'm',
        unit: TIMES,
      },
    ],
    stacks: ['DO'],
    behavior: { primitive: 'control.repeat' },
    codegen: {
      js: 'for (let i = 0; i < {times}; i++) {\n{DO}\n}',
      py: 'for i in range({times}):\n{DO}',
    },
  },
  {
    type: 'control_forever',
    category: 'control',
    tier: 2,
    shape: 'wrapper',
    icon: 'infinity',
    label: 'Всегда',
    voice: 'повторять всегда',
    params: [],
    stacks: ['DO'],
    behavior: { primitive: 'control.forever' },
    codegen: { js: 'while (true) {\n{DO}\n}', py: 'while True:\n{DO}' },
  },
  {
    type: 'event_tap',
    category: 'events',
    tier: 2,
    shape: 'hat',
    icon: 'pointer',
    label: 'Когда тап',
    voice: 'когда нажали на героя',
    params: [],
    behavior: { primitive: 'event.tap' },
    codegen: { js: 'onTap(() => {\n{STACK}\n});', py: '@on_tap\ndef on_tap():\n{STACK}' },
  },
  {
    type: 'event_touch',
    category: 'events',
    tier: 2,
    shape: 'hat',
    icon: 'hand',
    label: 'Касается',
    voice: 'когда касается',
    voiceTemplate: 'когда касается: {what}',
    params: [
      {
        name: 'what',
        kind: 'choice',
        voice: 'чего коснуться',
        options: TOUCH_TARGETS,
        default: 'actor',
      },
    ],
    behavior: { primitive: 'event.touch' },
    codegen: {
      js: 'onTouch({what}, () => {\n{STACK}\n});',
      py: '@on_touch({what})\ndef on_touch():\n{STACK}',
    },
  },
  {
    type: 'looks_hide',
    category: 'looks',
    tier: 2,
    shape: 'command',
    icon: 'eye-off',
    label: 'Спрятаться',
    voice: 'спрятаться',
    params: [],
    behavior: { primitive: 'looks.visible', with: { visible: false } },
    codegen: { js: 'hide();', py: 'hide()' },
  },
  {
    type: 'looks_show',
    category: 'looks',
    tier: 2,
    shape: 'command',
    icon: 'eye',
    label: 'Показаться',
    voice: 'показаться',
    params: [],
    behavior: { primitive: 'looks.visible', with: { visible: true } },
    codegen: { js: 'show();', py: 'show()' },
  },
  {
    type: 'looks_costume',
    category: 'looks',
    tier: 2,
    shape: 'command',
    icon: 'shirt',
    label: 'Костюм',
    voice: 'сменить костюм',
    voiceTemplate: 'костюм: {costume}',
    params: [
      {
        name: 'costume',
        kind: 'dynamic',
        voice: 'какой костюм',
        source: 'costumes',
        default: 'next',
      },
    ],
    behavior: { primitive: 'looks.costume' },
    codegen: { js: 'switchCostume({costume});', py: 'switch_costume({costume})' },
  },
];
